# Generated by Django 4.2.6 on 2026-03-15 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('armor_type', models.CharField(choices=[('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy')], max_length=6)),
                ('description', models.TextField(max_length=512)),
                ('durability', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='armor_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='armor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=2048)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artifact_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artifact_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('starting_hp', models.IntegerField()),
                ('starting_fate_points', models.IntegerField(default=2)),
                ('vitality', models.IntegerField(default=10)),
                ('endurance', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('attunement', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('faith', models.IntegerField(default=10)),
                ('has_special_rules', models.BooleanField(default=False)),
                ('special_rules', models.TextField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinyFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cost', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=16384)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[('TOOL', 'Tool'), ('AMMO', 'Ammunition'), ('MATERIAL', 'Crafting Material'), ('BOOK', 'Spell or Weapon Skill Book'), ('MISC', 'Miscellaneous')], max_length=8)),
                ('range', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(max_length=2048)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('subtitle', models.CharField(help_text="Short descriptor (e.g., 'Wayfarers of Death', 'Masters of the Hollowed Earth')", max_length=100)),
                ('description', models.TextField(help_text='Full lineage lore and background description', max_length=4096)),
                ('appearance', models.TextField(help_text='Physical appearance and distinguishing features', max_length=1024)),
                ('language', models.CharField(help_text='Primary language spoken by this lineage', max_length=60)),
                ('lifespan_min', models.IntegerField(help_text='Minimum lifespan in years')),
                ('lifespan_max', models.IntegerField(help_text='Maximum lifespan in years')),
                ('base_abilities', models.JSONField(help_text='Stores lineage abilities as JSON. Example for Ferno lineage: {"vision": {"type": "darkvision", "range": 60}, "skill_bonuses": {"Sanity": 2}, "special_abilities": [{"name": "Auto-detect Undying", "description": "Automatically detect undying stacks on visible creatures", "type": "passive"}], "regeneration": {"hp": {"base": "1d2/hour", "condition": "in full darkness", "scaling": [{"level": 17, "value": "1d4/hour"}]}}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tier', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=2048)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ring_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ring_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_time', models.CharField(max_length=200)),
                ('ap', models.IntegerField(default=0)),
                ('fp', models.IntegerField(default=0)),
                ('range', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_official', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('SOUL_CRYSTAL', 'Soul/Crystal Sorcery'), ('FROST', 'Frost Sorcery'), ('ASSASSIN_LIGHT', 'Assassin/Light Sorcery'), ('COSMIC', 'Cosmic Sorcery'), ('DARK', 'Dark Hex'), ('DEBUFF_HEX', 'Debuffing Hex'), ('BLOOD', 'Blood Hex'), ('DEATH', 'Death Hex'), ('TIME', 'Time Magic'), ('HEALING', 'Healing Miracle'), ('LIGHTNING', 'Lightning Miracle'), ('BUFF_DEF_MIRACLE', 'Buffing and Defensive Miracle'), ('FORCE', 'Force Miracle'), ('FIRE', 'Fire Pyromancy'), ('DRAGON', 'Dragon Pyromancy'), ('PESTILENCE', 'Pestilence Pyromancy'), ('BUFF_DEBUFF_PYRO', 'Buffing and Debuffing Pyromancy'), ('DARKFROST_BLACKFIRE', 'Darkfrost/Blackfire Hex')], max_length=20)),
                ('is_slow', models.BooleanField(default=False)),
                ('att_cost', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spell_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spell_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('tier', models.CharField(choices=[('ONE', 'Tier One'), ('TWO', 'Tier Two'), ('THREE', 'Tier Three'), ('FOUR', 'Tier Four')], default='ONE', max_length=5)),
                ('creature', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.CharField(choices=[('TINY', 'Tiny'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('MASSIVE', 'Massive'), ('GARGANTUAN', 'Gargantuan'), ('ASTRONOMICAL', 'Astronomical')], default='MEDIUM', max_length=12)),
                ('range', models.CharField(blank=True, default='', max_length=200)),
                ('condition', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('att_cost', models.IntegerField(default=1, help_text='Attunement slot cost')),
                ('fp', models.IntegerField(default=0, help_text='FP cost')),
                ('ap', models.IntegerField(default=0, help_text='AP cost')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spirit_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spirit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.IntegerField(default=0)),
                ('divisor', models.IntegerField(default=1)),
                ('multiplier', models.IntegerField(default=1)),
                ('modifier', models.CharField(choices=[('NON', 'None'), ('LVL', 'Level'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('SOD', 'Strength Or Dexterity'), ('SOI', 'Strength Or Intelligence'), ('SOF', 'Strength Or Faith'), ('DOI', 'Dexterity Or Intelligence'), ('DOF', 'Dexterity Or Faith'), ('EOA', 'Endurance Or Attunement'), ('IOF', 'Intelligence Or Faith')], default='NON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('is_trick', models.BooleanField(default=False)),
                ('is_twin', models.BooleanField(default=False)),
                ('weapon_type', models.CharField(choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT', 'Straight Sword'), ('THRUST', 'Thrusting Sword'), ('KATANA', 'Katana'), ('CURVED', 'Curved Sword'), ('GREAT_SWORD', 'Great Sword'), ('ULTRA_GREAT_SWORD', 'Ultra Great Sword'), ('AXE', 'Axe'), ('GREAT_AXE', 'Great Axe'), ('HAMMER', 'Hammer'), ('GREAT_HAMMER', 'Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSSBOW', 'Crossbow'), ('BOW', 'Bow'), ('GREAT_BOW', 'Great Bow'), ('BALLISTA', 'Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('GREAT_SHIELD', 'Great Shield'), ('STAFF', 'Staff'), ('TALISMAN', 'Talisman'), ('PYRO', 'Pyromancy Flame'), ('CRUCIBLE', 'Crucible'), ('WIND_INSTRUMENT', 'Wind Instrument'), ('STRING_INSTRUMENT', 'String Instrument'), ('PERCUSSION_INSTRUMENT', 'Percussion Instrument'), ('TONGUE_INSTRUMENT', 'Tongue Instrument'), ('HORN_INSTRUMENT', 'Horn Instrument')], max_length=25)),
                ('second_type', models.CharField(blank=True, choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT', 'Straight Sword'), ('THRUST', 'Thrusting Sword'), ('KATANA', 'Katana'), ('CURVED', 'Curved Sword'), ('GREAT_SWORD', 'Great Sword'), ('ULTRA_GREAT_SWORD', 'Ultra Great Sword'), ('AXE', 'Axe'), ('GREAT_AXE', 'Great Axe'), ('HAMMER', 'Hammer'), ('GREAT_HAMMER', 'Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSSBOW', 'Crossbow'), ('BOW', 'Bow'), ('GREAT_BOW', 'Great Bow'), ('BALLISTA', 'Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('GREAT_SHIELD', 'Great Shield'), ('STAFF', 'Staff'), ('TALISMAN', 'Talisman'), ('PYRO', 'Pyromancy Flame'), ('CRUCIBLE', 'Crucible'), ('WIND_INSTRUMENT', 'Wind Instrument'), ('STRING_INSTRUMENT', 'String Instrument'), ('PERCUSSION_INSTRUMENT', 'Percussion Instrument'), ('TONGUE_INSTRUMENT', 'Tongue Instrument'), ('HORN_INSTRUMENT', 'Horn Instrument')], default=None, max_length=25, null=True)),
                ('ap', models.IntegerField(default=3)),
                ('infusion', models.CharField(blank=True, choices=[('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark')], default=None, max_length=9, null=True)),
                ('second_ap', models.IntegerField(blank=True, default=None, null=True)),
                ('second_infusion', models.CharField(blank=True, choices=[('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark')], default=None, max_length=9, null=True)),
                ('description', models.TextField(max_length=512)),
                ('durability', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapon_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProfFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('weapon_tree', models.CharField(choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT_THRUST', 'Straight Sword/Thrusting Sword'), ('KATANA_CURVED', 'Katana/Curved Sword'), ('ULTRA_GREAT_SWORD', 'Great Sword/Ultra Great Sword'), ('GREAT_AXE', 'Axe/Great Axe'), ('GREAT_HAMMER', 'Hammer/Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSS_BOW', 'Bow/Crossbow'), ('GREAT_BOW_BALLISTA', 'Great Bow/Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('SORCERY', 'Sorcery'), ('MIRACLE', 'Miracle'), ('PYROMANCY', 'Pyromancy'), ('HEX', 'Hex'), ('SPIRIT_SUMMONING', 'Spirit Summoning'), ('DUAL_WIELDING', 'Dual Wielding'), ('MUSICAL_INSTRUMENTS', 'Musical Instruments')], max_length=20)),
                ('level', models.IntegerField(default=3)),
                ('description', models.TextField(max_length=4096)),
                ('usage_formula', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProfSubFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=4096)),
                ('extends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='compendium.weaponproffeat')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_feat', to='compendium.weaponproffeat')),
                ('usage_formula', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cost_fp', models.IntegerField(default=0)),
                ('is_slow', models.BooleanField(default=False)),
                ('usage_type', models.CharField(choices=[('MELEE', 'Melee Only'), ('RANGED', 'Ranged Only'), ('BOTH', 'Melee and Ranged'), ('CAST', 'Casting Implements Only'), ('MCAST', 'Melee and Casting Implements'), ('RCAST', 'Ranged and Casting Implements'), ('BCAST', 'Both and Casting Implements'), ('STANCE', 'Power Stance')], max_length=6)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorRequirements',
            fields=[
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('armor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='compendium.armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellCharged',
            fields=[
                ('cast_time', models.CharField(max_length=200)),
                ('ap', models.IntegerField(default=0)),
                ('fp', models.IntegerField(default=0)),
                ('range', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('base_spell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='charged', serialize=False, to='compendium.spell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellRequirements',
            fields=[
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('spell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='compendium.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritRequirements',
            fields=[
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('spirit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='compendium.spirit')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSkillScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('weapon_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weaponskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponSkillDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('weapon_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weaponskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponSkillBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weaponskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark')], max_length=9)),
                ('stat', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('form', models.CharField(choices=[('primary', 'Primary Form'), ('secondary', 'Secondary Form')], default='primary', max_length=9)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfSubScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weaponprofsubfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfSubDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weaponprofsubfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfSubBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weaponprofsubfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weaponproffeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weaponproffeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weaponproffeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('form', models.CharField(choices=[('primary', 'Primary Form'), ('secondary', 'Secondary Form')], default='primary', max_length=9)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='weapon',
            name='second_skill_primary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon_second_skill_primary', to='compendium.weaponskill'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='second_skill_secondary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon_second_skill_secondary', to='compendium.weaponskill'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='skill_primary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.weaponskill'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='skill_secondary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon_skill_secondary', to='compendium.weaponskill'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapon_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weapon',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='SpiritReduceBuildup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildup_type', models.CharField(choices=[('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frost'), ('CURSE', 'Curse'), ('POISE', 'Poise')], max_length=10)),
                ('dice_count', models.IntegerField(default=0, help_text='Number of dice (e.g., 1 for 1d4)')),
                ('dice_value', models.IntegerField(default=0, help_text='Dice sides (e.g., 4 for 1d4)')),
                ('flat_bonus', models.IntegerField(default=0, help_text='Flat amount added to roll')),
                ('scaling_source', models.JSONField(blank=True, default=dict, help_text='Optional scaling source')),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduce_buildup', to='compendium.spirit')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.spirit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpiritDamageProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark')], max_length=10)),
                ('tiers', models.IntegerField(default=0)),
                ('flat', models.IntegerField(default=0)),
                ('dice_count', models.IntegerField(default=0)),
                ('dice_value', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('percentage_timing', models.CharField(choices=[('INITIAL', 'Before Reductions'), ('FINAL', 'After Reductions')], default='FINAL', max_length=7)),
                ('duration_turns', models.IntegerField(default=0)),
                ('duration_attacks', models.IntegerField(default=0)),
                ('apply_to_caster', models.BooleanField(default=False)),
                ('apply_to_target', models.BooleanField(default=True)),
                ('stacking', models.CharField(choices=[('APPEND', 'Append'), ('OVERWRITE', 'Overwrite')], default='OVERWRITE', max_length=9)),
                ('scaling_source', models.JSONField(blank=True, default=dict)),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_protection', to='compendium.spirit')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritConditionProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('GRAPPLED', 'Grappled'), ('RESTRAINED', 'Restrained'), ('PRONE', 'Prone'), ('MOUNTING', 'Mounting'), ('IMPAIRED_VISION', 'Impaired Vision'), ('DEAFENED', 'Deafened'), ('DAZED', 'Dazed'), ('LIMB_FRACTURE', 'Limb Fracture'), ('LOCKED_UP', 'Locked Up'), ('FRENZY', 'Frenzy'), ('BERSERK', 'Berserk'), ('EXHAUSTION', 'Exhaustion'), ('STAGGERED', 'Staggered'), ('BLED_OUT', 'Bled Out'), ('POISONED', 'Poisoned'), ('BADLY_POISONED', 'Badly Poisoned'), ('FROSTBITTEN', 'Frostbitten'), ('CURSED', 'Cursed')], max_length=20)),
                ('duration_turns', models.IntegerField(default=0)),
                ('apply_to_caster', models.BooleanField(default=False)),
                ('apply_to_target', models.BooleanField(default=True)),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_protection', to='compendium.spirit')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritBuildupProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frost'), ('CURSE', 'Curse'), ('POISE', 'Poise')], max_length=10)),
                ('flat', models.IntegerField(default=0)),
                ('dice_count', models.IntegerField(default=0)),
                ('dice_value', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('percentage_timing', models.CharField(choices=[('INITIAL', 'Before Reductions'), ('FINAL', 'After Reductions')], default='FINAL', max_length=7)),
                ('duration_turns', models.IntegerField(default=0)),
                ('duration_attacks', models.IntegerField(default=0)),
                ('apply_to_caster', models.BooleanField(default=False)),
                ('apply_to_target', models.BooleanField(default=True)),
                ('stacking', models.CharField(choices=[('APPEND', 'Append'), ('OVERWRITE', 'Overwrite')], default='OVERWRITE', max_length=9)),
                ('scaling_source', models.JSONField(blank=True, default=dict)),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildup_protection', to='compendium.spirit')),
            ],
        ),
        migrations.CreateModel(
            name='SpellScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('requirement', models.IntegerField(default=0)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('form', models.CharField(choices=[('primary', 'Primary Form'), ('secondary', 'Secondary Form')], default='primary', max_length=9)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_scaling', to='compendium.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='SpellReduceBuildup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildup_type', models.CharField(choices=[('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frost'), ('CURSE', 'Curse'), ('POISE', 'Poise')], max_length=10)),
                ('dice_count', models.IntegerField(default=0, help_text='Number of dice (e.g., 1 for 1d4)')),
                ('dice_value', models.IntegerField(default=0, help_text='Dice sides (e.g., 4 for 1d4)')),
                ('flat_bonus', models.IntegerField(default=0, help_text='Flat amount added to roll')),
                ('scaling_source', models.JSONField(blank=True, default=dict, help_text='Optional scaling source')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduce_buildup', to='compendium.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.spell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellDamageProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark')], max_length=10)),
                ('tiers', models.IntegerField(default=0)),
                ('flat', models.IntegerField(default=0)),
                ('dice_count', models.IntegerField(default=0)),
                ('dice_value', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('percentage_timing', models.CharField(choices=[('INITIAL', 'Before Reductions'), ('FINAL', 'After Reductions')], default='FINAL', max_length=7)),
                ('duration_turns', models.IntegerField(default=0)),
                ('duration_attacks', models.IntegerField(default=0)),
                ('apply_to_caster', models.BooleanField(default=False)),
                ('apply_to_target', models.BooleanField(default=True)),
                ('stacking', models.CharField(choices=[('APPEND', 'Append'), ('OVERWRITE', 'Overwrite')], default='OVERWRITE', max_length=9)),
                ('scaling_source', models.JSONField(blank=True, default=dict)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_protection', to='compendium.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellConditionProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('GRAPPLED', 'Grappled'), ('RESTRAINED', 'Restrained'), ('PRONE', 'Prone'), ('MOUNTING', 'Mounting'), ('IMPAIRED_VISION', 'Impaired Vision'), ('DEAFENED', 'Deafened'), ('DAZED', 'Dazed'), ('LIMB_FRACTURE', 'Limb Fracture'), ('LOCKED_UP', 'Locked Up'), ('FRENZY', 'Frenzy'), ('BERSERK', 'Berserk'), ('EXHAUSTION', 'Exhaustion'), ('STAGGERED', 'Staggered'), ('BLED_OUT', 'Bled Out'), ('POISONED', 'Poisoned'), ('BADLY_POISONED', 'Badly Poisoned'), ('FROSTBITTEN', 'Frostbitten'), ('CURSED', 'Cursed')], max_length=20)),
                ('duration_turns', models.IntegerField(default=0)),
                ('apply_to_caster', models.BooleanField(default=False)),
                ('apply_to_target', models.BooleanField(default=True)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_protection', to='compendium.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellBuildupProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frost'), ('CURSE', 'Curse'), ('POISE', 'Poise')], max_length=10)),
                ('flat', models.IntegerField(default=0)),
                ('dice_count', models.IntegerField(default=0)),
                ('dice_value', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('percentage_timing', models.CharField(choices=[('INITIAL', 'Before Reductions'), ('FINAL', 'After Reductions')], default='FINAL', max_length=7)),
                ('duration_turns', models.IntegerField(default=0)),
                ('duration_attacks', models.IntegerField(default=0)),
                ('apply_to_caster', models.BooleanField(default=False)),
                ('apply_to_target', models.BooleanField(default=True)),
                ('stacking', models.CharField(choices=[('APPEND', 'Append'), ('OVERWRITE', 'Overwrite')], default='OVERWRITE', max_length=9)),
                ('scaling_source', models.JSONField(blank=True, default=dict)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildup_protection', to='compendium.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.spell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RingScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.ring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RingDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.ring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RingBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.ring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ring',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='ItemScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinyScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('destiny_feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.destinyfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='destinyfeat',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='DestinyDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('destiny_feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.destinyfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinyBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('destiny_feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.destinyfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='ArmorBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('is_innate', models.BooleanField(default=False)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='WeaponRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('form', models.CharField(choices=[('primary', 'Primary Form'), ('secondary', 'Secondary Form')], default='primary', max_length=9)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compendium.weapon')),
            ],
            options={
                'unique_together': {('weapon', 'form')},
            },
        ),
        migrations.CreateModel(
            name='SpiritCureEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('BLEED', 'Bleed (cures Bled Out)'), ('POISON', 'Poison (cures Poisoned)'), ('TOXIC', 'Toxic (cures Badly Poisoned)'), ('FROST', 'Frost (cures Frostbitten)'), ('CURSE', 'Curse (cures Cursed)'), ('POISE', 'Poise (cures Staggered)')], max_length=10)),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cure_effects', to='compendium.spirit')),
            ],
            options={
                'unique_together': {('spirit', 'effect_type')},
            },
        ),
        migrations.CreateModel(
            name='SpiritCureCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('GRAPPLED', 'Grappled'), ('RESTRAINED', 'Restrained'), ('PRONE', 'Prone'), ('MOUNTING', 'Mounting'), ('IMPAIRED_VISION', 'Impaired Vision'), ('DEAFENED', 'Deafened'), ('DAZED', 'Dazed'), ('LIMB_FRACTURE', 'Limb Fracture'), ('LOCKED_UP', 'Locked Up'), ('FRENZY', 'Frenzy'), ('BERSERK', 'Berserk'), ('EXHAUSTION', 'Exhaustion')], max_length=20)),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cure_conditions', to='compendium.spirit')),
            ],
            options={
                'unique_together': {('spirit', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='SpellCureEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('BLEED', 'Bleed (cures Bled Out)'), ('POISON', 'Poison (cures Poisoned)'), ('TOXIC', 'Toxic (cures Badly Poisoned)'), ('FROST', 'Frost (cures Frostbitten)'), ('CURSE', 'Curse (cures Cursed)'), ('POISE', 'Poise (cures Staggered)')], max_length=10)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cure_effects', to='compendium.spell')),
            ],
            options={
                'unique_together': {('spell', 'effect_type')},
            },
        ),
        migrations.CreateModel(
            name='SpellCureCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('GRAPPLED', 'Grappled'), ('RESTRAINED', 'Restrained'), ('PRONE', 'Prone'), ('MOUNTING', 'Mounting'), ('IMPAIRED_VISION', 'Impaired Vision'), ('DEAFENED', 'Deafened'), ('DAZED', 'Dazed'), ('LIMB_FRACTURE', 'Limb Fracture'), ('LOCKED_UP', 'Locked Up'), ('FRENZY', 'Frenzy'), ('BERSERK', 'Berserk'), ('EXHAUSTION', 'Exhaustion')], max_length=20)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cure_conditions', to='compendium.spell')),
            ],
            options={
                'unique_together': {('spell', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='SpellChargedDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('DAMAGE_FP', 'FP Damage'), ('DAMAGE_AP', 'AP Damage'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('FROST', 'Frostbite'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('HEAL', 'HP Healing'), ('RESTORE_FP', 'FP Restoration'), ('RESTORE_AP', 'AP Restoration'), ('VARYING', 'Varying'), ('DURABILITY', 'Durability')], max_length=10)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.spellcharged')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellChargedBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.spellcharged')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bloodline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Bloodline name (e.g., 'Death Touched Ferno', 'Geode Grme')", max_length=60)),
                ('description', models.TextField(help_text='Full bloodline description and what makes it unique', max_length=2048)),
                ('replaces_abilities', models.JSONField(blank=True, default=list, help_text='List of base lineage ability keys that this bloodline removes. The bloodline provides replacement abilities via new_abilities. Example for Death Touched Ferno: ["regeneration"]')),
                ('new_abilities', models.JSONField(blank=True, default=dict, help_text='Abilities this bloodline grants (replaces removed abilities). Uses same structure as base_abilities. Example for Death Touched Ferno: {"special_abilities": [{"name": "Ghostflame Respawn", "description": "Can respawn in place on successful undying check via white ghostflame", "type": "passive"}], "regeneration": {"hp": {"base": "-1d2/hour", "condition": "in bright light"}}}')),
                ('has_unlock_requirement', models.BooleanField(default=False, help_text='Check if this bloodline requires special conditions to unlock')),
                ('unlock_requirement', models.TextField(blank=True, help_text='What the player must do to unlock this bloodline. Leave blank for bloodlines available at character creation. Example for Ancient Scale Dragonkind: "Regular Dragonkind level 10+ with communion of 3+ ancient dragon types"', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineage', models.ForeignKey(help_text='The parent lineage this bloodline belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bloodlines', to='compendium.lineage')),
            ],
            options={
                'ordering': ['lineage__name', 'name'],
                'unique_together': {('lineage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ArtifactUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this upgrade (e.g., 'Flame Infusion', 'Dark Path')", max_length=200)),
                ('unlock_requirements', models.TextField(blank=True, help_text="Text describing what player must do to unlock (e.g., 'Defeat 10 enemies with fire magic')", max_length=2048)),
                ('visible', models.BooleanField(default=False, help_text='If true, player can see this upgrade exists. If false, completely hidden from player.')),
                ('requirements_visible', models.BooleanField(default=False, help_text='If true, player can see the unlock requirements. If false, requirements are hidden even if upgrade is visible.')),
                ('description', models.TextField(help_text='What this upgrade does (visible to player if visible=true)', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(help_text='The artifact this upgrade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='compendium.artifact')),
                ('influenced_destiny_feats', models.ManyToManyField(blank=True, help_text='Destiny feats this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.destinyfeat')),
                ('influenced_spells', models.ManyToManyField(blank=True, help_text='Spells this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.spell')),
                ('influenced_weapon_prof_feats', models.ManyToManyField(blank=True, help_text='Weapon proficiency feats this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.weaponproffeat')),
                ('influenced_weapon_skills', models.ManyToManyField(blank=True, help_text='Weapon skills this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.weaponskill')),
            ],
            options={
                'ordering': ['artifact__name', 'name'],
                'unique_together': {('artifact', 'name')},
            },
        ),
    ]
