# Generated by Django 4.2.6 on 2024-05-06 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('armor_type', models.CharField(choices=[('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy')], max_length=6)),
                ('description', models.TextField(max_length=512)),
                ('durability', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='armor_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='armor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=2048)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artifact_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artifact_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinyFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cost', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=16384)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[('TOOL', 'Tool'), ('AMMO', 'Ammunition'), ('MATERIAL', 'Crafting Material'), ('BOOK', 'Spell or Weapon Skill Book'), ('MISC', 'Miscellaneous')], max_length=8)),
                ('range', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(max_length=2048)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tier', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=2048)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ring_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ring_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_time', models.CharField(max_length=200)),
                ('ap', models.IntegerField(default=0)),
                ('fp', models.IntegerField(default=0)),
                ('range', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_official', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('SOUL_CRYSTAL', 'Soul/Crystal Sorcery'), ('FROST', 'Frost Sorcery'), ('ASSASSIN_LIGHT', 'Assassin/Light Sorcery'), ('COSMIC', 'Cosmic Sorcery'), ('DARK', 'Dark Hex'), ('DEBUFF_HEX', 'Debuffing Hex'), ('BLOOD', 'Blood Hex'), ('DEATH', 'Death Hex'), ('TIME', 'Time Magic'), ('HEALING', 'Healing Miracle'), ('LIGHTNING', 'Lightning Miracle'), ('BUFF_DEF_MIRACLE', 'Buffing and Defensive Miracle'), ('FORCE', 'Force Miracle'), ('FIRE', 'Fire Pyromancy'), ('DRAGON', 'Dragon Pyromancy'), ('PESTILENCE', 'Pestilence Pyromancy'), ('BUFF_DEBUFF_PYRO', 'Buffing and Debuffing Pyromancy'), ('DARKFROST_BLACKFIRE', 'Darkfrost/Blackfire Hex')], max_length=20)),
                ('is_slow', models.BooleanField(default=False)),
                ('att_cost', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spell_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spell_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.IntegerField(default=0)),
                ('divisor', models.IntegerField(default=1)),
                ('multiplier', models.IntegerField(default=1)),
                ('modifier', models.CharField(choices=[('NON', 'None'), ('LVL', 'Level'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('SOD', 'Strength Or Dexterity'), ('SOI', 'Strength Or Intelligence'), ('SOF', 'Strength Or Faith'), ('DOI', 'Dexterity Or Intelligence'), ('DOF', 'Dexterity Or Faith'), ('EOA', 'Endurance Or Attunement'), ('IOF', 'Intelligence Or Faith')], default='NON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('is_trick', models.BooleanField(default=False)),
                ('is_twin', models.BooleanField(default=False)),
                ('weapon_type', models.CharField(choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT', 'Straight Sword'), ('THRUST', 'Thrusting Sword'), ('KATANA', 'Katana'), ('CURVED', 'Curved Sword'), ('GREAT_SWORD', 'Great Sword'), ('ULTRA_GREAT_SWORD', 'Ultra Great Sword'), ('AXE', 'Axe'), ('GREAT_AXE', 'Great Axe'), ('HAMMER', 'Hammer'), ('GREAT_HAMMER', 'Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSSBOW', 'Crossbow'), ('BOW', 'Bow'), ('GREAT_BOW', 'Great Bow'), ('BALLISTA', 'Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('GREAT_SHIELD', 'Great Shield'), ('STAFF', 'Staff'), ('TALISMAN', 'Talisman'), ('PYRO', 'Pyromancy Flame'), ('CRUCIBLE', 'Crucible')], max_length=20)),
                ('second_type', models.CharField(blank=True, choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT', 'Straight Sword'), ('THRUST', 'Thrusting Sword'), ('KATANA', 'Katana'), ('CURVED', 'Curved Sword'), ('GREAT_SWORD', 'Great Sword'), ('ULTRA_GREAT_SWORD', 'Ultra Great Sword'), ('AXE', 'Axe'), ('GREAT_AXE', 'Great Axe'), ('HAMMER', 'Hammer'), ('GREAT_HAMMER', 'Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSSBOW', 'Crossbow'), ('BOW', 'Bow'), ('GREAT_BOW', 'Great Bow'), ('BALLISTA', 'Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('GREAT_SHIELD', 'Great Shield'), ('STAFF', 'Staff'), ('TALISMAN', 'Talisman'), ('PYRO', 'Pyromancy Flame'), ('CRUCIBLE', 'Crucible')], default=None, max_length=20, null=True)),
                ('ap', models.IntegerField(default=3)),
                ('description', models.TextField(max_length=512)),
                ('durability', models.IntegerField(default=10)),
                ('infusion', models.CharField(blank=True, choices=[('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark')], default=None, max_length=9, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapon_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProfFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('weapon_tree', models.CharField(choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT_THRUST', 'Straight Sword/Thrusting Sword'), ('KATANA_CURVED', 'Katana/Curved Sword'), ('ULTRA_GREAT_SWORD', 'Great Sword/Ultra Great Sword'), ('GREAT_AXE', 'Axe/Great Axe'), ('GREAT_HAMMER', 'Hammer/Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSS_BOW', 'Bow/Crossbow'), ('GREAT_BOW_BALLISTA', 'Great Bow/Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('SORCERY', 'Sorcery'), ('MIRACLE', 'Miracle'), ('PYROMANCY', 'Pyromancy'), ('HEX', 'Hex'), ('SPIRIT_SUMMONING', 'Spirit Summoning'), ('DUAL_WIELDING', 'Dual Wielding')], max_length=18)),
                ('level', models.IntegerField(default=3)),
                ('description', models.TextField(max_length=4096)),
                ('usage_formula', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProfSubFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=4096)),
                ('extends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='compendium.weaponproffeat')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_feat', to='compendium.weaponproffeat')),
                ('usage_formula', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cost_fp', models.IntegerField(default=0)),
                ('is_slow', models.BooleanField(default=False)),
                ('usage_type', models.CharField(choices=[('MELEE', 'Melee Only'), ('RANGED', 'Ranged Only'), ('BOTH', 'Melee and Ranged'), ('CAST', 'Casting Implements Only'), ('MCAST', 'Melee and Casting Implements'), ('RCAST', 'Ranged and Casting Implements'), ('BCAST', 'Both and Casting Implements'), ('STANCE', 'Power Stance')], max_length=6)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorRequirements',
            fields=[
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('armor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='compendium.armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellCharged',
            fields=[
                ('cast_time', models.CharField(max_length=200)),
                ('ap', models.IntegerField(default=0)),
                ('fp', models.IntegerField(default=0)),
                ('range', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('base_spell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='charged', serialize=False, to='compendium.spell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellRequirements',
            fields=[
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('spell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='compendium.spell')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponRequirements',
            fields=[
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('weapon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='compendium.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponSkillScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('weapon_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weaponskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponSkillDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('weapon_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weaponskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponSkillBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weaponskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TONE', 'Tier One Summon'), ('TTWO', 'Tier Two Summon'), ('TTHREE', 'Tier Three Summon'), ('TFOUR', 'Tier Four Summon')], max_length=9)),
                ('stat', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfSubScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weaponprofsubfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfSubDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weaponprofsubfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfSubBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weaponprofsubfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.weaponproffeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weaponproffeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weaponproffeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='weapon',
            name='skill_primary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.weaponskill'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='skill_secondary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon_skill_secondary', to='compendium.weaponskill'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapon_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weapon',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='SpellScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('requirement', models.IntegerField(default=0)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_scaling', to='compendium.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='SpellDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.spell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.spell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RingScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.ring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RingDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.ring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RingBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.ring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ring',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='ItemScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinyScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('destiny_feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.destinyfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='destinyfeat',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='DestinyDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('destiny_feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.destinyfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinyBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('destiny_feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.destinyfeat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('stat', models.CharField(choices=[('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith')], max_length=3)),
                ('value', models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='compendium.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='ArmorBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('is_innate', models.BooleanField(default=False)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='usage_formula',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compendium.usageformula'),
        ),
        migrations.CreateModel(
            name='SpellChargedDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.spellcharged')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellChargedBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAX_HP', 'Maximum HP'), ('MAX_AP', 'Maximum AP'), ('MAX_FP', 'Maximum FP'), ('VIT', 'Vitality'), ('END', 'Endurance'), ('STR', 'Strength'), ('DEX', 'Dexterity'), ('ATT', 'Attunement'), ('INT', 'Intelligence'), ('FAI', 'Faith'), ('ATH', 'Athletics'), ('ACR', 'Acrobatics'), ('PER', 'Perception'), ('FIR', 'Fire Keeping'), ('SAN', 'Sanity'), ('STE', 'Stealth'), ('PRE', 'Precision'), ('DIP', 'Diplomacy'), ('TIER_PHYSICAL', 'Physical Resistance Tier'), ('TIER_MAGIC', 'Magic Resistance Tier'), ('TIER_FIRE', 'Fire Resistance Tier'), ('TIER_LIGHTNING', 'Lightning Resistance Tier'), ('TIER_DARK', 'Dark Resistance Tier'), ('FLAT_PHYSICAL', 'Physical Resistance Flat'), ('FLAT_MAGIC', 'Magic Resistance Flat'), ('FLAT_FIRE', 'Fire Resistance Flat'), ('FLAT_LIGHTNING', 'Lightning Resistance Flat'), ('FLAT_DARK', 'Dark Resistance Flat'), ('FLAT_PHYS_PER_TIER', 'Flat Physical Resistance Per Tier'), ('FLAT_PHYS_PER_COMBAT', 'Flat Physical Resistance Once Per Combat'), ('CURSE', 'Curse'), ('FROST', 'Frost'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('POISE', 'Poise'), ('KNOW_MAGIC', 'Knowledge Magics'), ('KNOW_HISTORY', 'Knowledge World History'), ('KNOW_MONSTERS', 'Knowledge Monsters'), ('KNOW_COSMIC', 'Knowledge Cosmic'), ('ATT_SLOTS', 'Attunement Slots'), ('FREE_MOVE', 'Free Movement'), ('REGEN_HP', 'HP Regeneration'), ('REGEN_FP', 'FP Regeneration'), ('DODGE_DIST', 'Dodge Distance'), ('DODGE_EXTRA', 'Extra Dodges'), ('DODGE_PER_COMBAT', 'Bonus Dodges Per Combat'), ('MAX_INT', 'Maximum Intelligence'), ('MAX_FAI', 'Maximum Faith'), ('MAX_FP_VIT_PLUS', 'Vit Mod + Bonus To Max FP'), ('MAX_HP_VIT_TIMES', 'Bonus + Bonus * Vit Mod To Max HP'), ('ATH_SUCCESS', 'Auto Succeed Athletics Per Combat'), ('VIT_ATH', 'Vit Mod to Athletics'), ('VIT_ACR', 'Vit Mod to Acrobatics'), ('VIT_PER', 'Vit Mod to Perception'), ('VIT_FIR', 'Vit Mod to Fire Keeping'), ('VIT_SAN', 'Vit Mod to Sanity'), ('VIT_STE', 'Vit Mod to Stealth'), ('VIT_PRE', 'Vit Mod to Precision'), ('VIT_DIP', 'Vit Mod to Diplomacy')], max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='compendium.spellcharged')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
