# Generated by Django 4.2.6 on 2025-11-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('starting_hp', models.IntegerField()),
                ('starting_fate_points', models.IntegerField(default=2)),
                ('vitality', models.IntegerField(default=10)),
                ('endurance', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('attunement', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('faith', models.IntegerField(default=10)),
                ('has_special_rules', models.BooleanField(default=False)),
                ('special_rules', models.TextField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=4096)),
                ('appearance', models.TextField(max_length=1024)),
                ('language', models.CharField(max_length=60)),
                ('lifespan_min', models.IntegerField()),
                ('lifespan_max', models.IntegerField()),
                ('base_abilities', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_official', models.BooleanField(default=False)),
                ('tier', models.CharField(choices=[('ONE', 'Tier One'), ('TWO', 'Tier Two'), ('THREE', 'Tier Three'), ('FOUR', 'Tier Four')], default='ONE', max_length=5)),
                ('creature', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.CharField(choices=[('TINY', 'Tiny'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('MASSIVE', 'Massive'), ('GARGANTUAN', 'Gargantuan'), ('ASTRONOMICAL', 'Astronomical')], default='MEDIUM', max_length=12)),
                ('range', models.CharField(blank=True, default='', max_length=200)),
                ('condition', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spirit_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spirit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='artifactdice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='artifactscaling',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='destinydice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='destinyscaling',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='itemdice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='itemscaling',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ringdice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ringscaling',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='spellchargeddice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='spelldice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weapondice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weaponprofdice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weaponprofscaling',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weaponprofsubdice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weaponprofsubscaling',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weaponskilldice',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weaponskillscaling',
            name='type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10),
        ),
        migrations.CreateModel(
            name='SpiritRequirements',
            fields=[
                ('int', models.IntegerField(default=0)),
                ('fai', models.IntegerField(default=0)),
                ('spirit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='compendium.spirit')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MAGIC', 'Magic'), ('FIRE', 'Fire'), ('LIGHTNING', 'Lightning'), ('DARK', 'Dark'), ('TRUE', 'True Damage'), ('VARYING', 'Varying Damage Type'), ('REDUCE', 'Damage Reduction'), ('HEAL', 'HP Healing'), ('FOCUS', 'FP Regeneration'), ('UNFOCUS', 'FP Degeneration'), ('FROST', 'Frostbite'), ('BLEED', 'Bleed'), ('POISON', 'Poison'), ('TOXIC', 'Toxic'), ('CURSE', 'Curse'), ('POISE', 'Poise'), ('DURABILITY', 'Durability')], max_length=10)),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='compendium.spirit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bloodline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=2048)),
                ('replaces_abilities', models.JSONField(blank=True, default=list)),
                ('new_abilities', models.JSONField(blank=True, default=dict)),
                ('has_unlock_requirement', models.BooleanField(default=False)),
                ('unlock_requirement', models.TextField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodlines', to='compendium.lineage')),
            ],
            options={
                'ordering': ['lineage__name', 'name'],
                'unique_together': {('lineage', 'name')},
            },
        ),
    ]
