# Generated by Django 4.2.6 on 2026-03-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_status'),
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_armors', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_artifacts', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='background',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bloodline',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destinyfeat',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_items', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='lineage',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ring',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_rings', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='ring',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_spells', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='spirit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_spirits', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_weapons', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='weaponproffeat',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weaponskill',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
    ]
