# Generated by Django 4.2.6 on 2025-11-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0002_background_lineage_spirit_alter_artifactdice_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodline',
            name='description',
            field=models.TextField(help_text='Full bloodline description and what makes it unique', max_length=2048),
        ),
        migrations.AlterField(
            model_name='bloodline',
            name='has_unlock_requirement',
            field=models.BooleanField(default=False, help_text='Check if this bloodline requires special conditions to unlock'),
        ),
        migrations.AlterField(
            model_name='bloodline',
            name='lineage',
            field=models.ForeignKey(help_text='The parent lineage this bloodline belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bloodlines', to='compendium.lineage'),
        ),
        migrations.AlterField(
            model_name='bloodline',
            name='name',
            field=models.CharField(help_text="Bloodline name (e.g., 'Death Touched Ferno', 'Geode Grme')", max_length=60),
        ),
        migrations.AlterField(
            model_name='bloodline',
            name='new_abilities',
            field=models.JSONField(blank=True, default=dict, help_text='Abilities this bloodline grants (replaces removed abilities). Uses same structure as base_abilities. Example for Death Touched Ferno: {"special_abilities": [{"name": "Ghostflame Respawn", "description": "Can respawn in place on successful undying check via white ghostflame", "type": "passive"}], "regeneration": {"hp": {"base": "-1d2/hour", "condition": "in bright light"}}}'),
        ),
        migrations.AlterField(
            model_name='bloodline',
            name='replaces_abilities',
            field=models.JSONField(blank=True, default=list, help_text='List of base lineage ability keys that this bloodline removes. The bloodline provides replacement abilities via new_abilities. Example for Death Touched Ferno: ["regeneration"]'),
        ),
        migrations.AlterField(
            model_name='bloodline',
            name='unlock_requirement',
            field=models.TextField(blank=True, help_text='What the player must do to unlock this bloodline. Leave blank for bloodlines available at character creation. Example for Ancient Scale Dragonkind: "Regular Dragonkind level 10+ with communion of 3+ ancient dragon types"', max_length=512),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='appearance',
            field=models.TextField(help_text='Physical appearance and distinguishing features', max_length=1024),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='base_abilities',
            field=models.JSONField(help_text='Stores lineage abilities as JSON. Example for Ferno lineage: {"vision": {"type": "darkvision", "range": 60}, "skill_bonuses": {"Sanity": 2}, "special_abilities": [{"name": "Auto-detect Undying", "description": "Automatically detect undying stacks on visible creatures", "type": "passive"}], "regeneration": {"hp": {"base": "1d2/hour", "condition": "in full darkness", "scaling": [{"level": 17, "value": "1d4/hour"}]}}}'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='description',
            field=models.TextField(help_text='Full lineage lore and background description', max_length=4096),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='language',
            field=models.CharField(help_text='Primary language spoken by this lineage', max_length=60),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='lifespan_max',
            field=models.IntegerField(help_text='Maximum lifespan in years'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='lifespan_min',
            field=models.IntegerField(help_text='Minimum lifespan in years'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='subtitle',
            field=models.CharField(help_text="Short descriptor (e.g., 'Wayfarers of Death', 'Masters of the Hollowed Earth')", max_length=100),
        ),
        migrations.CreateModel(
            name='ArtifactUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this upgrade (e.g., 'Flame Infusion', 'Dark Path')", max_length=200)),
                ('unlock_requirements', models.TextField(blank=True, help_text="Text describing what player must do to unlock (e.g., 'Defeat 10 enemies with fire magic')", max_length=2048)),
                ('visible', models.BooleanField(default=False, help_text='If true, player can see this upgrade exists. If false, completely hidden from player.')),
                ('requirements_visible', models.BooleanField(default=False, help_text='If true, player can see the unlock requirements. If false, requirements are hidden even if upgrade is visible.')),
                ('description', models.TextField(help_text='What this upgrade does (visible to player if visible=true)', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(help_text='The artifact this upgrade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='compendium.artifact')),
                ('influenced_destiny_feats', models.ManyToManyField(blank=True, help_text='Destiny feats this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.destinyfeat')),
                ('influenced_spells', models.ManyToManyField(blank=True, help_text='Spells this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.spell')),
                ('influenced_weapon_prof_feats', models.ManyToManyField(blank=True, help_text='Weapon proficiency feats this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.weaponproffeat')),
                ('influenced_weapon_skills', models.ManyToManyField(blank=True, help_text='Weapon skills this upgrade affects', related_name='artifact_upgrade_influences', to='compendium.weaponskill')),
            ],
            options={
                'ordering': ['artifact__name', 'name'],
                'unique_together': {('artifact', 'name')},
            },
        ),
    ]
