# Generated by Django 4.2.6 on 2026-03-18 21:58

from django.db import migrations


def set_all_official(apps, schema_editor):
    """Set is_official=True for all existing compendium records."""
    models_to_update = [
        'Spell',
        'Spirit',
        'Item',
        'Ring',
        'Artifact',
        'Armor',
        'Weapon',
        'WeaponProfFeat',
        'DestinyFeat',
        'WeaponSkill',
        'Background',
        'Lineage',
        'Bloodline',
    ]

    for model_name in models_to_update:
        Model = apps.get_model('compendium', model_name)
        count = Model.objects.filter(is_official=False).update(is_official=True)
        if count > 0:
            print(f'  Set {count} {model_name} records to is_official=True')


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0002_armor_campaign_artifact_campaign_and_more'),
    ]

    operations = [
        migrations.RunPython(set_all_official, migrations.RunPython.noop),
    ]
