# Generated by Django 4.2.6 on 2026-03-31 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0003_remove_campaign_status'),
        ('compendium', '0003_set_existing_records_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponskill',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='If set, this weapon skill belongs to a specific campaign (custom)', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='weaponskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weaponskill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_weapon_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weaponskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='weaponskill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_weapon_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
