# Generated by Django 4.2.6 on 2025-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0003_add_artifact_upgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='second_type',
            field=models.CharField(blank=True, choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT', 'Straight Sword'), ('THRUST', 'Thrusting Sword'), ('KATANA', 'Katana'), ('CURVED', 'Curved Sword'), ('GREAT_SWORD', 'Great Sword'), ('ULTRA_GREAT_SWORD', 'Ultra Great Sword'), ('AXE', 'Axe'), ('GREAT_AXE', 'Great Axe'), ('HAMMER', 'Hammer'), ('GREAT_HAMMER', 'Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSSBOW', 'Crossbow'), ('BOW', 'Bow'), ('GREAT_BOW', 'Great Bow'), ('BALLISTA', 'Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('GREAT_SHIELD', 'Great Shield'), ('STAFF', 'Staff'), ('TALISMAN', 'Talisman'), ('PYRO', 'Pyromancy Flame'), ('CRUCIBLE', 'Crucible'), ('WIND_INSTRUMENT', 'Wind Instrument'), ('STRING_INSTRUMENT', 'String Instrument'), ('PERCUSSION_INSTRUMENT', 'Percussion Instrument'), ('TONGUE_INSTRUMENT', 'Tongue Instrument'), ('HORN_INSTRUMENT', 'Horn Instrument')], default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT', 'Straight Sword'), ('THRUST', 'Thrusting Sword'), ('KATANA', 'Katana'), ('CURVED', 'Curved Sword'), ('GREAT_SWORD', 'Great Sword'), ('ULTRA_GREAT_SWORD', 'Ultra Great Sword'), ('AXE', 'Axe'), ('GREAT_AXE', 'Great Axe'), ('HAMMER', 'Hammer'), ('GREAT_HAMMER', 'Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSSBOW', 'Crossbow'), ('BOW', 'Bow'), ('GREAT_BOW', 'Great Bow'), ('BALLISTA', 'Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('GREAT_SHIELD', 'Great Shield'), ('STAFF', 'Staff'), ('TALISMAN', 'Talisman'), ('PYRO', 'Pyromancy Flame'), ('CRUCIBLE', 'Crucible'), ('WIND_INSTRUMENT', 'Wind Instrument'), ('STRING_INSTRUMENT', 'String Instrument'), ('PERCUSSION_INSTRUMENT', 'Percussion Instrument'), ('TONGUE_INSTRUMENT', 'Tongue Instrument'), ('HORN_INSTRUMENT', 'Horn Instrument')], max_length=25),
        ),
        migrations.AlterField(
            model_name='weaponproffeat',
            name='weapon_tree',
            field=models.CharField(choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT_THRUST', 'Straight Sword/Thrusting Sword'), ('KATANA_CURVED', 'Katana/Curved Sword'), ('ULTRA_GREAT_SWORD', 'Great Sword/Ultra Great Sword'), ('GREAT_AXE', 'Axe/Great Axe'), ('GREAT_HAMMER', 'Hammer/Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSS_BOW', 'Bow/Crossbow'), ('GREAT_BOW_BALLISTA', 'Great Bow/Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('SORCERY', 'Sorcery'), ('MIRACLE', 'Miracle'), ('PYROMANCY', 'Pyromancy'), ('HEX', 'Hex'), ('SPIRIT_SUMMONING', 'Spirit Summoning'), ('DUAL_WIELDING', 'Dual Wielding'), ('MUSICAL_INSTRUMENT', 'Musical Instrument')], max_length=20),
        ),
    ]
