# Generated by Django 4.2.6 on 2025-12-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0004_alter_weapon_second_type_alter_weapon_weapon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='att_cost',
            field=models.IntegerField(default=1, help_text='Attunement slot cost'),
        ),
        migrations.AlterField(
            model_name='weaponproffeat',
            name='weapon_tree',
            field=models.CharField(choices=[('FIST', 'Fist'), ('DAGGER', 'Dagger'), ('STRAIGHT_THRUST', 'Straight Sword/Thrusting Sword'), ('KATANA_CURVED', 'Katana/Curved Sword'), ('ULTRA_GREAT_SWORD', 'Great Sword/Ultra Great Sword'), ('GREAT_AXE', 'Axe/Great Axe'), ('GREAT_HAMMER', 'Hammer/Great Hammer'), ('TWINBLADE', 'Twinblade'), ('SPEAR', 'Spear'), ('HALBERD', 'Halberd'), ('REAPER', 'Reaper'), ('WHIP', 'Whip'), ('CROSS_BOW', 'Bow/Crossbow'), ('GREAT_BOW_BALLISTA', 'Great Bow/Ballista'), ('GUN', 'Gun Sidearm'), ('SHIELD', 'Shield'), ('SORCERY', 'Sorcery'), ('MIRACLE', 'Miracle'), ('PYROMANCY', 'Pyromancy'), ('HEX', 'Hex'), ('SPIRIT_SUMMONING', 'Spirit Summoning'), ('DUAL_WIELDING', 'Dual Wielding'), ('MUSICAL_INSTRUMENTS', 'Musical Instruments')], max_length=20),
        ),
    ]
