# Generated by Django 4.2.6 on 2025-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0005_spirit_att_cost_alter_weaponproffeat_weapon_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='ap',
            field=models.IntegerField(default=0, help_text='AP cost'),
        ),
        migrations.AddField(
            model_name='spirit',
            name='fp',
            field=models.IntegerField(default=0, help_text='FP cost'),
        ),
    ]
