# Generated by Django 4.2.6 on 2026-03-15 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_type', models.CharField(choices=[('patreon', 'Patreon Member'), ('permanent', 'Permanent Member')], default='patreon', max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('patreon_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('patreon_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patreon_access_token', models.TextField(blank=True, null=True)),
                ('patreon_refresh_token', models.TextField(blank=True, null=True)),
                ('subscription_status', models.CharField(blank=True, choices=[('active_patron', 'Active Patron'), ('declined_patron', 'Declined Patron'), ('former_patron', 'Former Patron'), ('never_patron', 'Never Patron')], default='never_patron', max_length=50, null=True)),
                ('subscription_tier', models.CharField(blank=True, max_length=100, null=True)),
                ('last_charge_date', models.DateTimeField(blank=True, null=True)),
                ('last_charge_status', models.CharField(blank=True, max_length=50, null=True)),
                ('account_locked', models.BooleanField(default=False)),
                ('lock_date', models.DateTimeField(blank=True, null=True)),
                ('grace_period_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_characters', models.IntegerField(default=10)),
                ('max_campaigns_as_gm', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
