# Generated by Django 4.2.6 on 2026-07-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authtoken_drop_profile_token_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('auto_locked', 'Auto locked (Patreon lapsed)'), ('manually_locked', 'Manually locked (admin)'), ('unlocked', 'Unlocked'), ('grace_started', 'Grace period started'), ('grace_notified', 'User acknowledged grace notification'), ('patreon_confirmed', 'Patreon status refreshed to active'), ('patreon_dropped', 'Patreon status dropped from active'), ('signup_rejected', 'Signup rejected (not a patron)')], max_length=32)),
                ('old_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(blank=True, default='', max_length=32)),
                ('old_lock_date', models.DateTimeField(blank=True, null=True)),
                ('new_lock_date', models.DateTimeField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='authtoken',
            new_name='accounts_au_user_id_b6d838_idx',
            old_name='accounts_au_user_id_source_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lock_reason',
            field=models.CharField(blank=True, choices=[('', 'None'), ('patreon_lapsed', 'Patreon lapsed'), ('admin_action', 'Admin action')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.userprofile'),
        ),
        migrations.AddIndex(
            model_name='accountauditlog',
            index=models.Index(fields=['profile', '-timestamp'], name='accounts_ac_profile_68bce0_idx'),
        ),
    ]
