# Generated by Django 4.2.6 on 2026-03-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_update_weapon_prof_max_and_companion_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterresources',
            name='destiny_feat_slots',
        ),
    ]
