# Generated by Django 4.2.6 on 2026-03-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_destiny_feat_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercompanion',
            name='companion_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='charactercompanion',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
