# Generated by Django 4.2.6 on 2026-03-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_companion_allow_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_category', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='characters.character')),
            ],
            options={
                'verbose_name': 'Character Inventory Item',
                'verbose_name_plural': 'Character Inventory Items',
                'unique_together': {('character', 'item_id', 'item_category')},
            },
        ),
    ]
