# Generated by Django 4.2.6 on 2026-03-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_status'),
        ('characters', '0005_characterinventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCampaignMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_assignments', to='campaigns.campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='characters.character')),
            ],
            options={
                'verbose_name': 'Character Campaign Membership',
                'verbose_name_plural': 'Character Campaign Memberships',
                'unique_together': {('character', 'campaign')},
            },
        ),
    ]
