# Generated by Django 4.2.6 on 2026-03-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_charactercampaignmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
