# Generated by Django 4.2.6 on 2026-03-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_change_image_url_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterobtainedfeat',
            name='source_feat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
