# Generated by Django 4.2.6 on 2026-03-15 01:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('max_players', models.IntegerField(default=6)),
                ('allow_spectators', models.BooleanField(default=False)),
                ('invite_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invite_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_session', models.DateTimeField(blank=True, null=True)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_campaigns', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('player', 'Player'), ('spectator', 'Spectator')], default='player', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('left', 'Left'), ('kicked', 'Kicked')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Campaign Membership',
                'verbose_name_plural': 'Campaign Memberships',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_a7762f_idx'), models.Index(fields=['user', 'status'], name='campaigns_c_user_id_22df0a_idx')],
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('player', 'Player'), ('spectator', 'Spectator')], default='player', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='campaigns.campaign')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='accounts.userprofile')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Campaign Invite',
                'verbose_name_plural': 'Campaign Invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invited_user', 'status'], name='campaigns_c_invited_f253c3_idx'), models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_88f7a2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['gm', 'status'], name='campaigns_c_gm_id_4d63f6_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['invite_code'], name='campaigns_c_invite__b252b2_idx'),
        ),
    ]
