# Generated by Django 4.2.6 on 2026-03-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='allow_spectators',
        ),
        migrations.AlterField(
            model_name='campaigninvite',
            name='role',
            field=models.CharField(choices=[('player', 'Player')], default='player', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignmembership',
            name='role',
            field=models.CharField(choices=[('player', 'Player')], default='player', max_length=20),
        ),
    ]
