# Generated by Django 4.2.6 on 2026-03-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_spectator_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_c_gm_id_4d63f6_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['gm'], name='campaigns_c_gm_id_6f95a2_idx'),
        ),
    ]
